image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - master
  script:
    - npm install
    - ./Tutorial/my-application/node_modules/@angular/cli/bin/ng test --progress false --single-run=true --watch=false
    - ./Tutorial/my-application/node_modules/@angular/cli/bin/ng e2e --progress false --watch=false
